spring:
  application:
    name: libry-io
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:libry}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:libry}
    password: ${DB_PASSWORD:libry}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  security:
    user:
      name: huy
      password: 1234

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.hibernate.SQL: info
